baseURL: https://blog.fangwuxin.com/
title: 方勿信的取经之路
copyright: 'Copyright © 2025-{year} Wuxin Fang. All Rights Reserved.'
defaultContentLanguage: zh-hans
# hasCJKLanguage: true # Uncomment it if your content contains Chinese/Japanese/Korean Languages.
# defaultContentLanguageInSubdir: true
# disableLanguages:
#  - fr
#  - zh-cn
#  - zh-tw
pagination:
  pagerSize: 10
# paginatePath: page
enableRobotsTXT: true
enableEmoji: true
pygmentsUseClasses: true

blackfriday:
  hrefTargetBlank: true

taxonomies:
  category: categories
  series: series
  tag: tags
  authors: authors

build:
  writeStats: true

permalinks:
  news: /news/:year/:month/:title/
  blog: /blog/:year/:month/:title/

module:
  imports:
    - path: github.com/razonyang/hugo-theme-bootstrap
  proxy: https://goproxy.cn

# services:
#   disqus:
#     shortname: your-disqus-shortname

markup:
  highlight:
    guessSyntax: true
    lineNos: true
    noClasses: false
    lineNumbersInTable: false
  tableOfContents:
    ordered: false    # 禁用目录自动编号
  goldmark:
    renderer:
      unsafe: false
    parser:
      autoHeadingID: true
      autoHeadingIDType: github
    extensions:
      headingOffset: 0
  image:
    enableRaw: true


taxonomies:
  category: categories
  series: series
  tag: tags
  authors: authors
